version: "3.9"
services:
  aeong:
    image: mp4sini/aeong:latest
    tty: true
    stdin_open: true
    env_file: .env
    volumes:
      - ./results/aeong:/home/AeonG/tests/results/query_results
    command:
      - /bin/bash
      - -c
      - |
        ./t_smarbench_test.sh
