version: "3.9"
services:
  aeong:
    image: mp4sini/aeong:latest
    hostname: aeong
    container_name: aeong
    env_file:
      - ./../.env  
    volumes:
      - ./../results/aeong:/home/AeonG/tests/results/aeong/query_results
    command:
      - /bin/bash
      - -c
      - |
        ./t_smarbench_test.sh
